config/routes.rb
Throwback::Application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit]
  resources :dashboard, only: [:index]
  resources :memories, only: [:index, :edit, :destroy, :update]

  resources :contact, only: [:new, :create]
  get 'contact' => 'contacts#new'
  post 'contact' => 'contacts#create'

  resources :categories, only: [:show] do 
    resources :questions, only: [:index, :show]
  end

  resources :questions, only: [:index] do
    resources :memories, only: [:new, :create]
  end

  resources :questions, only: [:index] do
    resources :dna_questions, only: [:new, :create]
  end

  resources :testimonials, only: [:index]

  resources :samples, only: [:index]

  namespace :admin do
    root to: "admin#index"
    resources :questions, :categories, :users, :memories
  end

   root 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name

  has_many :questions,
    inverse_of: :category
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  before_action :set_category, except: [:index, :new, :create]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to admin_categories_path, notice: "Successfully added category."
    else
      render :new, notice: 'failure'
    end
  end


  def update
    if @category.update(category_params)
      redirect_to admin_categories_path
    else
      render action: 'edit'
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

end

app/views/admin/categories/edit.html.erb
<div class="border-form-div">
  <h1> Edit Category <h1>

<%= simple_form_for([:admin, @category]) do |f| %>
  <div class="form-inputs">
    <%= f.input :name, label: false, autofocus: true, placeholder: 'Category Name' %>
  </div><br>
  <div class="form-actions">
    <%= f.button :submit, "Save", :class => "btn btn-primary" %>
  </div>
<% end %>
<br>

</div>

app/views/admin/categories/index.html.erb
<table class="table table-striped">
  <thead>
    <td><h1>Category - <%= link_to 'New Category', new_admin_category_path %></h1></td>
      <tbody>
        <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td><%= category.id %></td>
          <td><%= link_to "Edit", edit_admin_category_path(category) %></td>
          <td><%= button_to "Remove", admin_category_path(category), method: :delete, data: {confirm: "Are you sure?" } %>
        </tr>
        <% end %>
        <%= link_to "Admin Home", admin_root_path %>
      <tbody>
</table>

app/views/admin/categories/new.html.erb
<div class="border-form-div">
  <h1> New Category <h1>

<%= simple_form_for([:admin, @category]) do |f| %>
  <div class="form-inputs">
    <%= f.input :name, label: false, autofocus: true, placeholder: 'Category Name' %>
  </div><br>
  <div class="form-actions">
    <%= f.button :submit, "Save", :class => "btn btn-primary" %>
  </div>
<% end %>
<br>

</div>