config/routes.rb
Throwback::Application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit]
  resources :dashboard, only: [:index]
  resources :memories, only: [:index, :edit, :destroy, :update]

  resources :contact, only: [:new, :create]
  get 'contact' => 'contacts#new'
  post 'contact' => 'contacts#create'

  resources :categories, only: [:show] do 
    resources :questions, only: [:index, :show]
  end

  resources :questions, only: [:index] do
    resources :memories, only: [:new, :create]
  end

  resources :questions, only: [:index] do
    resources :dna_questions, only: [:new, :create]
  end

  resources :testimonials, only: [:index]

  resources :samples, only: [:index]

  namespace :admin do
    root to: "admin#index"
    resources :questions, :categories, :users, :memories
  end

   root 'welcome#index'

end

app/models/memory.rb
class Memory < ActiveRecord::Base
  validates_presence_of :body, :user, :question, :year, :season

  validates :year, numericality: { greater_than: 1900, less_than: 2015}

  belongs_to :question,
    inverse_of: :memories

  belongs_to :user,
    inverse_of: :memories

  validates :question, uniqueness: { scope: :user }

  default_scope order: 'memories.year DESC'
  scope :year, lambda{|year| where('year = ?', year)}
  scope :category, lambda{|category| where('category = ?', category)}
  scope :season, lambda{|season| where('season = ?', season)}
  
end

app/controllers/admin/memories_controller.rb
class Admin::MemoriesController < Admin::AdminController
  before_action :set_memory, except: [:index]

  def index
    @memories = Memory.all
  end

  def destroy
    @memory.destroy
    redirect_to admin_memories_path
  end

private

def set_memory
  @memory = Memory.find(params[:id])
end
  
end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_memory, only: [:destroy, :show, :update, :edit]
  has_scope :year
  has_scope :question
  has_scope :season

  def index
    @memories = apply_scopes(current_user.memories).paginate(page: params[:page], per_page: 3)
  end

  def new
    @question = Question.find(params[:question_id])
    @user = current_user.id
    @memory = @question.memories.build
  end

  def show
  end

  def edit
  end

  def update
    if @memory.update(memory_params)
      redirect_to memories_path
    else
      render action: 'edit'
    end
  end

  def create
    @question = Question.find(params[:question_id])
    @memory = current_user.memories.build(memory_params)

    if @memory.save
      redirect_to dashboard_index_path, notice: "Successfully added memory."
    else
      render :new, notice: 'failure'
    end
  end

  def destroy
    @memory.destroy
    redirect_to memories_path
  end

private
  
  def memory_params
    params.require(:memory).permit(:body, :user_id, :question_id, :year, :season)
  end

  def set_memory
    @memory = Memory.find(params[:id])
  end

end

app/views/memories/edit.html.erb
<div class="row">
<%= simple_form_for @memory do |f| %>
  <%= f.input_field :body, label: false, required: true, placeholder: "Capture Memory Here", class: "form-control input-lg", :rows =>"10" %>
</div>
<br>
 <br>
    <span class="help-block"><i>Year and Season are not required, but will help to put your memories in the correct order for display in your timeline.  Consider estimating.  You can always edit later.</i></span>
    <br>
  <div class="row">
    <div class="col-xs-4 col-md-4">
  <%= f.input_field :year, collection: 1935..2014, prompt: 'Year', class: "form-control input-lg" %>
    </div>
    <div class="col-xs-4 col-md-4">
  <%= f.input_field :season, collection: ['Late Winter', 'Spring', 'Summer', 'Fall', 'Early Winter'], prompt: 'Season', :class =>"form-control input-lg" %>
    </div>

  <%= f.button :submit, "Save", class: "btn btn-lg btn-success pull-right" %>
  <%= link_to "Cancel", :back, class: "btn btn-lg btn-danger pull-right" %>

</div>

  <% end %>

app/views/memories/index.html.erb
<div class="jumbotron">
  <ul class="nav pull-right">
    <li><p><%= link_to "See All", memories_path%></p></li>
  </ul>
    <h1>Timeline</h1>
</div>

<% @memories.each do |memory| %>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1 class="panel-title"><%= memory.question.question %></h1>
  </div>
  <div class="panel-body">
    <p class="lead"><%= memory.body %></p>
      <ul class="nav nav-justified">
        <p class="text-muted">Tags</p>
          <li><%= link_to memory.question.category.name, {controller: 'memories', action: 'index', category: memory.question.category} %></li>
          <li><%= link_to memory.year, {controller: 'memories', action: 'index', year: memory.year} %></li>
          <li><%= link_to memory.season, {controller: 'memories', action: 'index', season: memory.season} %></li>
          <li><p><%= link_to "Edit Memory", edit_memory_path(memory), class: "btn btn-sm btn-primary pull-right" %></p></li>
          <li><p><%= link_to "Delete Memory", memory, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-sm btn-danger pull-right" %></p></li>
      </ul>
  </div>
</div>
  <% end %>

  <%= will_paginate @memories, renderer: BootstrapPagination::Rails %>

app/views/memories/new.html.erb
<div class="jumbotron">
  <h1><%= @question.category.name %></h1><br>
  <p><%= @question.question %></p><br>
</div>

<div class="row">
<%= simple_form_for(@memory, :url => question_memories_path, :class =>'form') do |f| %>
  <%= f.input :question_id, :as => :hidden, value: @question.id %>
  <%= f.input :user_id, :as => :hidden, value: current_user.id %>
  <%= f.input_field :body, label: false, required: true, placeholder: "Capture Memory Here", class: "form-control input-lg", :rows =>"10" %>
</div>
<br>
 <br>
    <span class="help-block"><i>Year and Season will help to put your memories in the correct order for display in your timeline.  If you are uncertain, use a best guess.  You can always edit later.</i></span>
    <br>
  <div class="row">
    <div class="col-xs-4 col-md-4">
  <%= f.input_field :year, collection: 1935..2014, prompt: 'Year', required: true, class: "form-control input-lg" %>
    </div>
    <div class="col-xs-4 col-md-4">
  <%= f.input_field :season, collection: ['Late Winter', 'Spring', 'Summer', 'Fall', 'Early Winter'], prompt: 'Season', required: true, class: "form-control input-lg" %>
    </div>

  <%= f.button :submit, "Save", class: "btn btn-lg btn-success pull-right" %>
  <%= link_to "Cancel", :back, class: "btn btn-lg btn-danger pull-right" %>

</div>

  <% end %>