config/routes.rb
Throwback::Application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit]
  resources :dashboard, only: [:index]
  resources :memories, only: [:index, :edit, :destroy, :update]

  resources :contact, only: [:new, :create]
  get 'contact' => 'contacts#new'
  post 'contact' => 'contacts#create'

  resources :categories, only: [:show] do 
    resources :questions, only: [:index, :show]
  end

  resources :questions, only: [:index] do
    resources :memories, only: [:new, :create]
  end

  resources :questions, only: [:index] do
    resources :dna_questions, only: [:new, :create]
  end

  resources :testimonials, only: [:index]

  resources :samples, only: [:index]

  namespace :admin do
    root to: "admin#index"
    resources :questions, :categories, :users, :memories
  end

   root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_save :mailchimp_status
  
  validates_presence_of :first_name, :last_name, :role, :birth_month, :birth_year, :birth_day

  has_many :memories,
    inverse_of: :user,
    dependent: :destroy

  has_many :questions,
    through: :memories

  has_many :dna_questions,
    inverse_of: :user

  def is_admin?
    role == 'admin'
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def mailchimp_status
    @mailchimp_list_id = ENV["mailchimp_list_id"]
    @gb = Gibbon::API.new
      @gb.lists.subscribe({
      :id => @mailchimp_list_id,
      :email => {:email => self.email},
      :merge_vars => {
        :FNAME => self.first_name,
        :LNAME => self.last_name,
        :BIRTHDAY => self.birth_year
      },
      :double_optin => false,
      :send_welcome => false
    })
  end

  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  before_action :set_user, except: [:index]

  def index
    @users = User.all
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path
  end

private

  def set_user
    @user = User.find(params[:id])
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def edit
    @user = current_user
  end

  def show
    @user = User.find(current_user[:id])
  end

  def update
    @user = User.new(user_params)

    if @user.update(user_params)
      redirect_to user_path(current_user), notice: "Profile successfully updated"
    else
      render action: 'edit'
    end
  end

private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :birth_year, :birth_month, :birth_day)
  end

  def user_authorization
    redirect_to(root_path) unless current_user.id == params[:id]
  end

end

app/views/admin/users/index.html.erb
<table class="table table-striped">
  <thead>
    <td><h1>Users</h1></td>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.email %></td>
          <td><%= user.birth_month %></td>
          <td><%= user.birth_day %></td>
          <td><%= user.birth_year %></td>
          <td><%= user.memories.count %></td>
          <td><%= link_to "Edit", edit_user_registration_path(user) %></td>
          <td><%= button_to "Remove", admin_user_path(user), method: :delete, data: {confirm: "Are you sure?" } %>
        </tr>
        <% end %>
      <tbody>
        <%= link_to "Admin Home", admin_root_path %>
</table>